# This is the dev docker compose that I use with docky for dev purpose
# Do not forget to create the mounted directory before
networks:
  default:
    external:
      name: dy
services:
  db:
    image: mongo:3
    volumes:
      - ./data/db:/data/db
      - ./data/backup:/backup
  locomotive:
    environment:
      - VIRTUAL_HOST=shopinvader-server.dy
      - VIRTUAL_PORT=3000
      - RAILS_ENV=development
      - STORE_ASSET_IN_S3=false
      - DRAGON_FLY_SECRET=thisISaDEMOkeyNOTsecret
      - LOCOMOTIVE_ENABLE_REGISTRATION=true
    image: quay.io/akretion/docky-ruby:latest
    links:
      - db
    volumes:
       - ./shopinvader:/workspace
       - ../gems:/workspace/dev-gem
       - ./bundle:/usr/local/bundle
       - ./data/tmp:/workspace/tmp
       - ./data/log:/workspace/log
       - ./data/public/sites:/workspace/public/sites
       - ./data/public/uploaded_assets:/workspace/public/uploaded_assets
    labels:
      docky.user: ubuntu
      docky.main.service: True
version: '3'
