# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1737ab05ca0671055dfde63111d302bbd23f5957697431e91f390d341c596f0a887c316755cb0ef1d1d62e90c9d8704dc1f6e84539d858dbd07af9f556fd7e5e

test:
  secret_key_base: 81118a61f67f2ab054bb6a9ae61d11002fd4bc8c873548ac5048ae970235af0b41e743af45243608c5ca43127142d26a7bad4ccf89348e94f999c3350ef1443c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
